apiVersion: v1
kind: Pod
metadata:
 name: dapi-test-pod
 namespace: myapp-dev
spec:
 containers:
   - name: test-container
     image: registry.k8s.io/busybox
     command: ["/bin/sh", "-c", "env"]
     env:
       - name: SPECIAL_LEVEL_KEY
         valueFrom:
           configMapKeyRef:
             name: my-config
             key: key1
       - name: SPECIAL_LEVEL_KEY_2
         valueFrom:
           configMapKeyRef:
             name: my-config
             key: key2
 restartPolicy: Never
