apiVersion: v1
kind: Pod
metadata:
 name: secret-test-pod
 namespace: myapp-dev
spec:
 containers:
   - name: test-container
     image: registry.k8s.io/busybox
     command: ["/bin/sh", "-c", "env"]
     env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: myweb-secret
            key: secret_username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: myweb-secret
            key: secret_password
 restartPolicy: Never
