apiVersion: v1
data:
  DB_URL: jdbc:postgresql://127.0.0.1:5432/dev
kind: ConfigMap
metadata:
  name: api-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: api-config
        image: nginx
        name: nginx
